CREATE DATABASE IF NOT EXISTS redis_reg;

USE redis_reg;

CREATE TABLE IF NOT EXISTS registers (
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    channel VARCHAR(50) NOT NULL,
    message TEXT NOT NULL,
    pub_redis TINYINT(1),
    date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
