version: '3'

networks:
  redisN:

services:
  frontend:
    image: nginx:1.13
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - redisN
    depends_on:
      - app
      - redis
  app:
    image: node:11.9
    volumes:
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
      - ./server.js:/app/server.js
      - ./index.html:/app/index.html
      - ./index.js:/app/index.js
    working_dir: /app
    # command: ["node", "index.js"]
    command: ["npm", "run", "dev"]
    networks:
      - redisN
    depends_on:
      - redis
  redis:
    image: redis
    networks:
      - redisN