version: '3'

networks:
  redisN:
  bancoN:

volumes:
  banco:

services:
  frontend:
    image: nginx:1.13
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - redisN
    depends_on:
      - app
      - redis
  app:
    image: node:11.9
    volumes:
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
      - ./server.js:/app/server.js
      - ./index.html:/app/index.html
    working_dir: /app
    # command: ["node", "index.js"]
    command: ["npm", "run", "dev"]
    networks:
      - redisN
      - bancoN
    depends_on:
      - redis
      - db
  redis:
    image: redis:5.0
    networks:
      - redisN
  db:
    image: mysql:8.0
    volumes:
      - banco:/var/lib/mysql
      - ./scripts:/scripts
      - ./banco/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bancoN
    environment:
      MYSQL_ROOT_PASSWORD: redis
      MYSQL_DATABASE: redis_reg